# Generated by Django 2.2.4 on 2020-05-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
