# Generated by Django 2.2.4 on 2020-05-28 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_remove_product_imagesrc'),
        ('userApp', '0003_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(related_name='wishlists', to='productApp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApp.Wishlist'),
        ),
    ]
