# Generated by Django 2.2.4 on 2020-05-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20200528_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wishlist',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='userApp.Wishlist'),
            preserve_default=False,
        ),
    ]
