# Generated by Django 2.2.4 on 2020-05-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_auto_20200528_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
