# Generated by Django 2.2.4 on 2020-05-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlists', to='productApp.Product'),
        ),
    ]
