# Generated by Django 2.2.4 on 2020-05-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_auto_20200528_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlists', to='productApp.Product'),
        ),
    ]
