# Generated by Django 2.2.4 on 2020-05-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageSrc',
            field=models.CharField(default='img/pc.jpg', max_length=45),
            preserve_default=False,
        ),
    ]
