# Generated by Django 2.2.4 on 2020-05-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0004_product_imagesrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageSrc',
        ),
    ]
